default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kadai007_rails_development
test:
  <<: *default
  database: kadai007_rails_test
 <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: kadai007_rails_production
  username: kadai007_rails
  password: <%= ENV['KADAI007_RAILS_DATABASE_PASSWORD'] %>
